name: React Native Build & Release

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.1.10909125

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install dependencies
        run: |
          npm install

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Android SDK
        id: cache-android-sdk
        uses: actions/cache@v3
        with:
          path: ${{ env.ANDROID_HOME }}
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Cache Android NDK
        id: cache-android-ndk
        uses: actions/cache@v3
        with:
          path: ${{ env.ANDROID_NDK_HOME }}
          key: ${{ runner.os }}-android-ndk-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-android-ndk-
      - name: Install Android SDK & NDK
        if: steps.cache-android-sdk.outputs.cache-hit != 'true' || steps.cache-android-ndk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '35.0.2'
          ndk-version: '26.1.10909125'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Android APK
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
